// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ccbupaednygmgxchkufl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjYnVwYWVkbnlnbWd4Y2hrdWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1MTI5MTUsImV4cCI6MjA4MDA4ODkxNX0.DLlQhdx2sKI-Azrf6cRZkTJBzgMb_qqi43gvFeL_T0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
