// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amoqcrnzqxktjiirhlse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtb3Fjcm56cXhrdGppaXJobHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTA1NTcsImV4cCI6MjA2MjY4NjU1N30.ut-UiHaHjHpytZNfr9k-0zomGpv2RG0dlc1jy3jGLMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);